### ISSUE TITLE
shouldComponentUpdate optimization prevents certain children from updating

### ISSUE THREAD

**Issue by genericsteele** [bokuweb/react-resizable-box#135]
### Overview of the problem

`Resizable` is preventing a child component from updating when its prop, which is an object, has a property change.

I'm using react-resizable-box 2.0.6

I am sure this issue is **not a duplicate**?

### Description

_I've made the props more generic for simplicity_

I'm using `<Resizable />` around a function that decides if a simple or complex version of a component should be used. The simple version is used most of the time, and only accepts a single `data` object prop. That `data` prop at a minimum contains a `value` property. 

* When the function is wrapped in `<Resizable />` and the `data.value` is changed upstream, the simple version of the component *does not re-render*.
* Without the function being wrapped in `<Resizable />`, when the `data.value` changes, the simple version of the component re-renders *correctly*. 
* When I directly render the simple version of the component as a child of `<Resizable />`(instead of choosing it in a function), the component updates *correctly* when the `data.value` changes upstream.
* When I pass `value` directly (instead of `data`) as a prop to the simple version generated from a function wrapped in `<Resizable />`, it re-renders *correctly* when `data.value` changes upstream.

### Theory

I was able to recreate the issue using a simple wrapping component that uses the same optimization in `shouldComponentUpdate` as `<Resizable />`:

```js
import React from 'react'
import isEqual from 'lodash/isEqual'

export default class ExampleBlockingWrapper extends React.Component {
  shouldComponentUpdate (nextProps, nextState) {
    return (
      !isEqual(this.props, nextProps) ||
      !isEqual(this.state, nextState)
    )
  }

  render () {
    return (
      <div>
        { this.props.children }
      </div>
    )
  }
}
```

This leads me to believe that this is an issue with lodash's `isEqual` being unable to detect deep/complex differences between `this.props.children` and `nextProps.children`.

### Proposed Solution

Sure, I can change my code to work within the constraints of this library's optimization, but I don't think that's a good long-term solution. A component that _wraps around children_ is different than a parent component that _renders subcomponents_. Parent components can be optimized with your `!isEqual` strategy because only the props & state impact the subcomponents. Wrapper components accept the children as a prop, which can make detecting equality very complex.

I found [this answer](https://discuss.reactjs.org/t/shouldcomponentupdate-and-children/2055/7) to [this question about optimizing wrappers](https://discuss.reactjs.org/t/shouldcomponentupdate-and-children/2055) helpful in understanding what was going on.

With React 16 on the horizon, I propose that we remove the optimization in `Resizable`'s `shouldComponentUpdate` in favor of allowing React to decide if a wrapper should allow its children to update.

**Comment by bokuweb** [comment]
@genericsteele Thanks for your report :)
I Agree with you. I think your opinion is completely correct.

`shouldUpdateComponet` has been removed in `react-resizable-box v3.0 (renamed "re-resizable")`.You can try this version by `npm i re-resizable` for now.

Then I'm gonna remove `shouldUpdateComponet` from v2 too and release v2.0.7.

thanks.

**Comment by bokuweb** [comment]
publish as v2.1.0.

**Comment by genericsteele** [comment]
@bokuweb Thanks for hearing me out! Great job with this lib.
