### ISSUE TITLE
Error when trying to render

### ISSUE THREAD

**Issue by brianluong** [bokuweb/react-resizable-box#31]
When I try to render a Resizable component, I always throw this error.

invariant.js:39 Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `DraggableElementsContainer`.

How can I fix this?

**Comment by bokuweb** [comment]
@brianluong Hi.thanks.Can you show me a minimum of code to reproduce?

**Comment by brianluong** [comment]
I have a very basic application. Only one component and a render method.

I've tried 

<Resizable  ></Resizable>

and also different values for props to pass in, but it's still giving me that error.

Am I missing something?

**Comment by bokuweb** [comment]
@brianluong I do not know If you do not look at the code. what is your npm version.

**Comment by brianluong** [comment]
My NPM version is 3.3.12.
Thank you for your help. I'm new to this.

**Comment by bokuweb** [comment]
Ummmmmm, it works on my env(npm2 and npm3)

```
import React, { Component } from 'react';
import Box from 'react-resizable-box';

export default class Example extends Component {
  render() {
    return (
      <Box customStyle={{ background: '#333', pasdding: '10px' }}>
        test
      </Box>
    );
  }
}
```


```
import React from 'react';
import { render } from 'react-dom';
import Example from './example';

render(<Example />, document.querySelector('#root'));
```

**Comment by brianluong** [comment]
`var React = require('react');
var ReactDOM = require('react-dom');
var ReactDnD = require('react-dnd');
var Resizable = require('react-resizable-box');


var MainApplication =  React.createClass({

	

	render : function() {
		return (
			<div>

				<Resizable></Resizable>
			</div>
		);
	}
});

ReactDOM.render(<MainApplication/>, document.getElementById('main'));`

**Comment by bokuweb** [comment]
@brianluong Uhhhh... please use bellow

```
var Resizable = require('react-resizable-box').default;
```

**Comment by brianluong** [comment]
> @brianluong Uhhhh... please use bellow

> var Resizable = require('react-resizable-box').default;

I have done this and I am still getting the error.

**Comment by brianluong** [comment]
Any other ideas?

**Comment by bokuweb** [comment]
it works on my env.

```
var React = require('react');
var ReactDOM = require('react-dom');
var ReactDnD = require('react-dnd');
var Resizable = require('react-resizable-box').default;


var MainApplication =  React.createClass({



  render : function() {
    return (
      <div>

        <Resizable></Resizable>
      </div>
    );
  }
});

ReactDOM.render(<MainApplication/>, document.getElementById('root'));
```


Or use `import` instead of `require`

**Comment by brianluong** [comment]
Message when I installed the module. Could the error come from conflicts with installed node modules?

![image](https://cloud.githubusercontent.com/assets/6441090/14532319/a75df43e-022e-11e6-9aa7-e90efb810a1c.png)

**Comment by brianluong** [comment]
OK it actually works if I add `.default`.

Can you explain why this is the case?

Thanks!

**Comment by bokuweb** [comment]
Babel6 transpile `export defalut class Resizable extends Component {} ` to `exports.default = Risizable;`
