### ISSUE TITLE
Not compatible with IE11 (and IE9/10)

### ISSUE THREAD

**Issue by bdyetton** [bokuweb/react-resizable-box#34]
Object.assign() is not supported by IE11 (and previous versions also). 
`Object doesn't support property or method 'assign'`
is thrown when attempting to render in IE11.

Is there a change you could replace Object.assign with a polyfill or something? I've tried to do it on my end with no luck :(

**Comment by bokuweb** [comment]
@bdyetton thx, I'll fix it

**Comment by bokuweb** [comment]
fixed v1.2.1

**Comment by bdyetton** [comment]
Thanks!

Regards,
Ben Yetton

Graduate Student,
Mednick Sleep and Cognition Lab,
University Of California, Riverside
900 University Ave
Riverside, CA 92521
benjamin.yetton@email.ucr.edu
