### ISSUE TITLE
Selecting inner text while resizing

### ISSUE THREAD

**Issue by Mackiavelli** [bokuweb/react-resizable-box#35]
I don't think that it's very useful to be able to select inner text while you are resizing. For instance, you can start resizing the left side to become smaller by dragging it to the right. That will change the cursor mid-drag to a text selector one and select the inner contents. I think that the cursor should be consistent through the drag process and not be able to select the text.

**Comment by bokuweb** [comment]
@saggiyogesh fixed. v1.3.1 released.
