### ISSUE TITLE
Adding custom class on resize handler

### ISSUE THREAD

**Issue by saggiyogesh** [bokuweb/react-resizable-box#37]
There is no possibility to add custom class on resize handler. 
Like I have enabled only `bottomRight` to handle drag, so I need to add some custom class on the div created for the bottomRight resize handler.

**Comment by bokuweb** [comment]
@saggiyogesh fixed. v1.3.1 released.

**Comment by travisdahl** [comment]
Hi there, just started using this and i don't see any of these classnames.

![image](https://cloud.githubusercontent.com/assets/379314/24527647/f891c168-1557-11e7-87ea-243b2b5257d3.png)

**Comment by travisdahl** [comment]
Sorry, Just found it in the code `handleClass`. Seems the docs need to be updated

**Comment by Mareeshss** [comment]
How to handle the right side only using handlecomponent , Still i cant see any class name
