### ISSUE TITLE
Is it possible to lock the aspect ratio anyhow?

### ISSUE THREAD

**Issue by ricardometring** [bokuweb/react-resizable-box#41]
I tried setting the width, height in the onResize function, but it seems to change the resizable-box container to the dragging values before I update the width and height via onResize.

Any ideas on how I could keep the aspect ratio of the resizable-box container?

**Comment by bokuweb** [comment]
@ricardometring Thanks your report. I think that there is a need to change the `react-resizable-box` code. Add new option, foe example `fixAspectRatio: PropTypes.bool`. When  `fixAspectRatio` set, save aspect ratio when onResizeStart called. Then, calculate size with aspect ratio and set on`onResize` callback.

**Comment by bokuweb** [comment]
@ricardometring Add `lockAspectRatio` props. Please use v1.5.1+.
