### ISSUE TITLE
Pass custom props to the container div without whitelisting

### ISSUE THREAD

**Issue by maksis** [bokuweb/react-resizable-box#45]
I need to pass props to the container div that aren't currently "whitelisted" by the component (such as `id`). Since the div container doesn't really contain any special logic, could it make sense to pass all unconsumed props to the div element as they are?

````
    const { componentProp1, componentProp2, ... , ...other  } = this.props;
    return (
      <div
        ref="resizable"
        style={{
          ...
        }}
        {...other}
...
```

**Comment by maksis** [comment]
... or add `containerProps` or similar prop for unfiltered passthrough

**Comment by bokuweb** [comment]
@maksis thanks for your report. I’ll consider it.

**Comment by bokuweb** [comment]
@maksis thanks for your report.  Add `extendsProps` and publish as v1.8.0.
