### ISSUE TITLE
lockAspectRatio resize glitch

### ISSUE THREAD

**Issue by ioRekz** [bokuweb/react-resizable-box#49]
Hello, I noticed some jump/glitch when resizing an element with aspectRatio true

Looking at the code 
https://github.com/bokuweb/react-resizable-box/blob/master/src/index.js#L174

I don't understand why there is this check. Removing it and updating both width and height solve my case.
I will make a PR as soon as I understand why you needed this check

**Comment by bokuweb** [comment]
@ioRekz Thanks for your report.
Ummm, It may not be necessary....
Would you make PR?

**Comment by bokuweb** [comment]
published. 🎉
