### ISSUE TITLE
Check min width / height when aspect ratio locked.

### ISSUE THREAD

**Issue by bokuweb** [bokuweb/react-resizable-box#53]
It is not working properly...

**Comment by sereschen** [comment]
Any progress on this?

**Comment by bokuweb** [comment]
@sereschen I've implemented this on v2.0.0-rc.1.
If you try this feature, please install `npm install react-resizable-box@2.0.0-rc.1`

**Comment by bokuweb** [comment]
Fix on @2.0-rc.2
