### ISSUE TITLE
Why is the NPMJS README empty?

### ISSUE THREAD

**Issue by steelbrain** [bokuweb/react-resizable-box#54]
Hi @bokuweb 

Thanks for writing this component, I'm using it in my [`linter-ui-default`](https://atom.io/packages/linter-ui-default). I visit the npmjs readme sometimes to read about the API and it's empty. Can you please make sure to include the README with the next update?

<img width="413" alt="screen shot 2017-03-24 at 5 59 32 pm" src="https://cloud.githubusercontent.com/assets/4278113/24295261/af228184-10bb-11e7-981f-3c697a5f423f.png">

**Comment by bokuweb** [comment]
Hi @steelbrain 

Thanks!!

According to [npm/registry#120 (comment)](https://github.com/npm/registry/issues/120#issuecomment-276157329), old versions of npm didn't include README.md. I'll fix it.thanks.

**Comment by bokuweb** [comment]
fixed. thanks!!
