### ISSUE TITLE
Any reason why angles' cursors are all swapped?

### ISSUE THREAD

**Issue by lorenzos** [bokuweb/react-resizable-box#56]
I noticed that the cursors used in angles' `style` are all swapped. For example, [here](https://github.com/bokuweb/react-resizable-box/blob/60ab1d35ca09fd213ec94cb796feb959bf047c71/src/resizer.js#L42) the south-west `sw-resize` cursor is used for the `topRight` angle.

I guess on Window (and maybe Mac) this is not noticeable since the `ne` icon is probably the same used for `sw` (i.e. a double-arrow line going from the top right to the bottom left), but on other OSes icons can be different. For example, here's what I see on Ubuntu:

![byzanz-record](https://cloud.githubusercontent.com/assets/245615/24350839/0eb2e128-12e4-11e7-85c8-416f8b3a25fc.gif)

**Comment by bokuweb** [comment]
There are probably no reasons. I think that it is a mistake.

**Comment by bokuweb** [comment]
published 🎉
