### ISSUE TITLE
Using <Resizable/> inside <Resizable/> 

### ISSUE THREAD

**Issue by ovionlogis** [bokuweb/react-resizable-box#77]
Is it possible to use an Resizable component inside another Resizable component?

I tried to make the parent element with the ability to change its height and the child element with the possibility of changing its width. In this case, the width of the child element does not work correctly. At the first change of width nothing happens, the subsequent changes always lag behind one change.

working demo https://codesandbox.io/s/3lnZ2rPXr

**Comment by bokuweb** [comment]
Please use `onResize` insteadOf `onResizeStop`

https://codesandbox.io/s/31WyzOwnn

**Comment by ovionlogis** [comment]
@bokuweb thank you for your prompt response, this solved my problem
