### ISSUE TITLE
Incorrect width logic in componentWillReceiveProps

### ISSUE THREAD

**Issue by maksis** [bokuweb/react-resizable-box#85]
The current logic in [`componentWillReceiveProps`](https://github.com/bokuweb/react-resizable-box/blob/master/src/index.js#L193) doesn't look correct: `newWidth` is taken from `this.props.width` instead of the newly provided props.

It causes lag when controlling the width manually via props, which I'm currently doing to make corrections if the browser window is resized to not to fit the whole resizable container: https://github.com/airdcpp-web/airdcpp-webui/blob/master/src/routes/Sidebar/components/Sidebar.jsx#L62 (http://webdemo.airdcpp.net)

**Comment by bokuweb** [comment]
@maksis Thanks for your report.I'll do investigation.

**Comment by bokuweb** [comment]
@maksis Please try @2.0.4.
You might need to update width via using `setState` when window resized.

**Comment by maksis** [comment]
Thanks! It's working now.

I don't want to update the cached width in my component when the window is resized to allow the sidebar to be restored to it's original size when the window is expanded again.
