### ISSUE TITLE
Animate rotation

### ISSUE THREAD

**Issue by kelonye** [bokuweb/react-resizable-box#88]
Def not the right place to ask this but am porting my app https://cloudup.com/c1mknrqo_8f and any way to animate orientation change (as shown) with the `updateSize` hook?

**Comment by bokuweb** [comment]
@kelonye Thanks.  Sorry, I don't have any idea to animate with `updateSize`.
You can change `react-resizable-box` className via props. You might be able to animate by changing `className`.

**Comment by kelonye** [comment]
Am just putting this here in case someone else finds it useful:

```js

render() {
  const deg = isLandscape ? 0 : 90; 
  const style = {
      transitionDuration: '.4s',
      transform: `rotate(${deg}deg)`,
  };
  <Resizable style={style} />
}
```

**Comment by bokuweb** [comment]
@kelonye Thanks!! 👍
